apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "napapp.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "napapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "napapp.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "napapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: {{ include "napapp.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80