{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "napapp.serviceAccountName" . }}
  labels:
    {{- include "napapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
